version: '3.9'
services:
  microservice-hospital:
    build:
      context: ./microservice-hospital/
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/dump
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./inuse-data:/data/db

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG